name: Packer check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: PACKER CHECKS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Packer init
        run: packer init .
        working-directory: ./packer

      - name: Packer Format Check
        run: |
          for template in $(find . -name '*.hcl'); do
             packer fmt "$template"
             if ! git diff --exit-code "$template"; then
               echo "Packer template $template is not correctly formatted."
               exit 1
             fi
           done
        working-directory: ./packer

      - name: Packer Validate
        run: |
          packer validate .
          if [ $? -ne 0 ]; then exit 1; fi
        working-directory: ./packer
